services:
  mariadb:
    build: mariadb/
    networks:
      - wp_net
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_password
    restart: always

  wordpress:
    build: wordpress/
    depends_on:
      - mariadb
    networks:
      - wp_net
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    secrets:
      - db_password
    restart: always

  nginx:
    build: nginx/
    depends_on:
      - wordpress
    networks:
      - wp_net
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    restart: always

volumes:
  db_data:
    driver_opts:
      type: none
      device: "/home/njooris/data/db/"
      o: bind
  wp_data:
    driver_opts:
      type: none
      device: "/home/njooris/data/wordpress/"
      o: bind

secrets:
  db_password:
    file: ./.secrets/db_password.txt

networks:
  wp_net:
    driver: bridge
